sonar.projectKey=Frontend
sonar.projectName=PayVault Frontend
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=src/tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=dist/**,node_modules/**,coverage/**,src/**/*.d.ts
sonar.coverage.exclusions=src/App.tsx,src/main.tsx,src/features/**,src/types/**,src/core/**,src/services/http/**,src/store/**,src/shared/hooks.ts,src/layouts/AppLayout.tsx,src/shared/components/ScratchCard.tsx
sonar.test.inclusions=src/tests/**/*.test.ts,src/tests/**/*.test.tsx

sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
